dist: trusty
sudo: false
os:
 - linux
language: d
d:
 - ldc
 - ldc-beta
matrix:
  allow_failures:
    - {d: ldc-beta}
branches:
  only:
    - master
script:
  # use -c openblas on newer ubuntu version
 - dub test -c unittest-blas
 - rm -rf .dub && dub build -c blas --build-mode=singleFile --build=better-c-release --force && g++ -std=c++14 example.cpp -L./ -lblas -llapack -lmir-optim && ./a.out
addons:
  apt:
    packages:
      # use openblas on newer ubuntu versions
      liblapack-dev
